# Generated by Django 6.0 on 2025-12-10 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_extend_perfume_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfume',
            name='notes',
        ),
    ]
