# Generated by Django 6.0 on 2025-12-10 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_old_notes_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfume',
            name='main_accords',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='perfume',
            name='occasions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='perfume',
            name='seasons',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
